"use client";

import { ArrowRight, Check, ChefHat, Clock3, Contact, Flame, GitBranch, Globe2, Minus, Pause, Play, Plus, RotateCcw, Scissors, Sparkles, Store, Thermometer, UserRound, Volume2, VolumeX } from "lucide-react";
import type { CSSProperties, DragEvent as ReactDragEvent, PointerEvent as ReactPointerEvent } from "react";
import { useMemo, useRef, useState } from "react";
import { DIFFICULTIES, INGREDIENTS, RECIPES, ingredientById, toppingSpriteById } from "@/lib/game-data";
import { arrivalInterval, isPrepComplete, type Action, type GameState, type Station } from "@/lib/game-state";

const spriteStyle=(id:string):CSSProperties=>{const sprite=toppingSpriteById.get(id)!;const col=sprite.index%sprite.columns,row=Math.floor(sprite.index/sprite.columns);return{backgroundImage:`url('${sprite.sheet==="main"?"/toppings-sprite-v2.png":"/toppings-extra-v2.png"}')`,backgroundSize:`${sprite.columns*100}% ${sprite.rows*100}%`,backgroundPosition:`${sprite.columns===1?0:col/(sprite.columns-1)*100}% ${sprite.rows===1?0:row/(sprite.rows-1)*100}%`}};
const avatarStyle=(index:number):CSSProperties=>({backgroundPosition:`${(index%3)*50}% ${Math.floor(index/3)*100}%`});

function Food({id}:{id:string}){return <i className="v2-food" style={spriteStyle(id)} aria-hidden="true"/>}

function Pizza({state,mode,onPlace,onCut}:{state:GameState;mode:"prep"|"oven"|"cut";onPlace?:(id:string,x:number,y:number)=>void;onCut?:(x1:number,y1:number,x2:number,y2:number)=>void}){
  const ref=useRef<HTMLDivElement>(null);const[start,setStart]=useState<{x:number;y:number}|null>(null);
  const coords=(event:{clientX:number;clientY:number})=>{const rect=ref.current!.getBoundingClientRect();return{x:(event.clientX-rect.left)/rect.width*100,y:(event.clientY-rect.top)/rect.height*100}};
  const valid=(x:number,y:number)=>Math.hypot(x-50,y-50)<46;
  const drop=(event:ReactDragEvent)=>{event.preventDefault();const p=coords(event),id=event.dataTransfer.getData("text/topping");if(id&&valid(p.x,p.y))onPlace?.(id,p.x,p.y)};
  return <div className={`v2-pizza-wrap ${mode}`}><div ref={ref} className={`v2-pizza ${state.cook>110?"burnt":""}`} style={{"--sauce":state.sauce/100,"--cheese":state.cheese/100,"--cook":Math.min(1,state.cook/110)} as CSSProperties} role="application" tabIndex={0} aria-label="Pizza workspace" onDragOver={event=>event.preventDefault()} onDrop={drop} onClick={event=>{if(mode!=="prep"||!state.selected)return;const p=coords(event);if(valid(p.x,p.y))onPlace?.(state.selected,p.x,p.y)}} onKeyDown={event=>{if(event.key==="Enter"&&mode==="prep"&&state.selected)onPlace?.(state.selected,50+Math.cos(state.placements.length*2.2)*27,50+Math.sin(state.placements.length*2.2)*27)}} onPointerDown={(event:ReactPointerEvent)=>{if(mode==="cut"){event.currentTarget.setPointerCapture(event.pointerId);setStart(coords(event))}}} onPointerUp={(event:ReactPointerEvent)=>{if(mode==="cut"&&start){const end=coords(event);onCut?.(start.x,start.y,end.x,end.y);setStart(null)}}}>
    <div className="v2-sauce"/><div className="v2-cheese"/>{state.placements.map((point,index)=><i key={`${point.id}-${index}`} className="v2-piece" style={{...spriteStyle(point.id),left:`${point.x}%`,top:`${point.y}%`,transform:`translate(-50%,-50%) rotate(${point.rotation}deg)`}}/>)}<div className="v2-bake"/>{state.cuts.map((cut,index)=><i className="v2-cut" key={index} style={{left:`${cut.x1}%`,top:`${cut.y1}%`,width:`${Math.hypot(cut.x2-cut.x1,cut.y2-cut.y1)}%`,transform:`rotate(${Math.atan2(cut.y2-cut.y1,cut.x2-cut.x1)*180/Math.PI}deg)`}}/>)}
  </div></div>;
}

const stationIcon={reception:Store,prep:ChefHat,oven:Flame,cut:Scissors};

export default function GameScreenV2({state,dispatch}:{state:GameState;dispatch:(action:Action)=>void}){
  const es=state.language==="es",recipe=RECIPES[state.recipeIndex],ready=isPrepComplete(state);
  const copy=es?{
    score:"Puntaje",patience:"Paciencia",orders:"Pedidos activos",next:"Próximo cliente",front:"Mostrador",prep:"Preparación",oven:"Hornos",cut:"Corte",
    order:"Comanda",client:"Cliente",requested:"La receta pide",take:"Tomar pedido",arriving:"Esperando nuevos clientes",prepHelp:"La receta es una guía, no un bloqueo: podés enviar una pizza incompleta y el cliente la evaluará.",sauce:"Salsa",cheese:"Queso",pantry:"Ingredientes",recipe:"Receta",extra:"Extra",undo:"Deshacer",send:"Enviar a un horno",full:"Los 3 hornos están ocupados",complete:"Receta completa",incomplete:"Pedido incompleto: podés continuar bajo tu responsabilidad",ovenHelp:"Los tres hornos siguen cocinando aunque cambies de pedido. Retirala cuando quieras: cruda, perfecta o quemada.",empty:"Vacío",heating:"Cocinando",paused:"Pausado",open:"Abrir",remove:"Retirar ahora",raw:"Cruda",cooking:"Cocinando",perfect:"Perfecta",burning:"Se quema",cutHelp:"Cortá arrastrando sobre la pizza o usá el corte preciso. También podés entregarla sin terminar.",precision:"Corte preciso",deliver:"Entregar pedido",result:"Pedido evaluado",nextOrder:"Atender otro pedido",redo:"Rehacer",repo:"Ver proyecto real",gamePortfolio:"Portfolio",waiting:"en espera",switchOrder:"Cambiar al pedido",noStation:"No hay pedidos en esta estación.",
  }:{
    score:"Score",patience:"Patience",orders:"Active orders",next:"Next customer",front:"Front counter",prep:"Preparation",oven:"Ovens",cut:"Cut",
    order:"Order ticket",client:"Client",requested:"Recipe calls for",take:"Take order",arriving:"Waiting for new customers",prepHelp:"The recipe is a guide, not a gate: you may send an incomplete pizza and the customer will score it.",sauce:"Sauce",cheese:"Cheese",pantry:"Ingredients",recipe:"Recipe",extra:"Extra",undo:"Undo",send:"Send to an oven",full:"All 3 ovens are occupied",complete:"Recipe complete",incomplete:"Incomplete order: continue at your own risk",ovenHelp:"All three ovens keep cooking while you work on other orders. Pull it whenever you want—raw, perfect, or burnt.",empty:"Empty",heating:"Baking",paused:"Paused",open:"Open",remove:"Pull it now",raw:"Raw",cooking:"Baking",perfect:"Perfect",burning:"Burning",cutHelp:"Cut by dragging across the pizza or use the precision cut. You may also deliver it unfinished.",precision:"Precision cut",deliver:"Deliver order",result:"Order evaluated",nextOrder:"Handle another order",redo:"Redo",repo:"View real project",gamePortfolio:"Portfolio",waiting:"waiting",switchOrder:"Switch to order",noStation:"No orders at this station.",
  };
  const stationLabels={reception:copy.front,prep:copy.prep,oven:copy.oven,cut:copy.cut};
  const progressFor=(index:number)=>index===state.recipeIndex?state:state.orderProgress[index];
  const statusFor=(index:number)=>progressFor(index)?.station??"reception";
  const stationCounts=(station:Exclude<Station,"result">)=>state.openOrders.filter(index=>statusFor(index)===station).length;
  const ovenForCurrent=state.ovenSlots.find(slot=>slot.recipeIndex===state.recipeIndex);
  const requiredCounts=recipe.ingredientIds.map(id=>state.placements.filter(point=>point.id===id).length);
  const pantry=useMemo(()=>{const required=recipe.ingredientIds.map(id=>ingredientById.get(id)!);const extra=INGREDIENTS.filter(item=>!recipe.ingredientIds.includes(item.id));return[...required,...extra.slice(state.recipeIndex,state.recipeIndex+4)]},[recipe,state.recipeIndex]);
  const place=(id:string,x:number,y:number)=>dispatch({type:"PLACE",placement:{id,x,y,rotation:Math.round(Math.random()*180)},correct:recipe.ingredientIds.includes(id)});
  const bakeState=state.cook<35?copy.raw:state.cook<76?copy.cooking:state.cook<=103?copy.perfect:copy.burning;
  const nextArrival=Math.max(0,Math.ceil(arrivalInterval(state.difficulty)-state.arrivalClock));
  const freeOven=state.ovenSlots.some(slot=>slot.recipeIndex===null);

  return <main className="classic-game">
    <header className="classic-header"><button className="classic-brand" onClick={()=>dispatch({type:"HOME"})}><span><ChefHat/></span><b>STACK &amp; SLICE<small>IGNACIO&apos;S DEV PIZZERIA</small></b></button><div className="classic-stats"><span><small>{copy.score}</small><b>{state.shiftScore.toString().padStart(6,"0")}</b></span><span><small>{copy.orders}</small><b>{state.openOrders.length}/5</b></span><span><small>{copy.patience}</small><b>{Math.ceil(state.patience)}s</b></span></div><div className="classic-tools"><button onClick={()=>dispatch({type:"LANG",language:es?"en":"es"})}><Globe2/>{es?"EN":"ES"}</button><button onClick={()=>dispatch({type:"TOGGLE_SOUND"})}>{state.sound?<Volume2/>:<VolumeX/>}</button><button onClick={()=>dispatch({type:"PORTFOLIO"})}><Sparkles/>{copy.gamePortfolio}</button></div></header>

    <section className="order-dock" aria-label={copy.orders}><div className="arrival-clock"><Clock3/><span>{copy.next}<b>{nextArrival}s</b></span></div><div className="order-tabs">{state.openOrders.map(index=>{const item=RECIPES[index],status=statusFor(index);return <button key={item.id} className={index===state.recipeIndex?"active":""} onClick={()=>dispatch({type:"SWITCH_ORDER",index})} aria-label={`${copy.switchOrder}: ${item.project}`}><i style={avatarStyle(item.customer.avatar)}/><span>{item.customer.name}<small>{item.project}</small></span><em>{stationLabels[status==="result"?"cut":status]}</em></button>})}</div><div className="dock-capacity"><UserRound/><b>{5-state.openOrders.length}</b><small>{copy.waiting}</small></div></section>

    <nav className="classic-stations" aria-label="Restaurant stations">{(["reception","prep","oven","cut"] as const).map((station,index)=>{const Icon=stationIcon[station],count=stationCounts(station);return <button key={station} className={state.station===station?"active":""} disabled={!count} onClick={()=>dispatch({type:"NAV_STATION",station})}><span>0{index+1}</span><Icon/><b>{stationLabels[station]}</b><em>{count}</em></button>})}</nav>

    <div className="classic-floor"><aside className="classic-ticket"><div className="ticket-pin"/><div className="classic-ticket-top"><b>{copy.order} #{String(state.recipeIndex+1).padStart(2,"0")}</b><span>{recipe.year}</span></div><small>{copy.client} · {recipe.customer.name}</small><h1>{recipe.project}</h1><p>{es?recipe.description:recipe.descriptionEn}</p><div className="ticket-dash"/><b className="ticket-label">{copy.requested}</b>{recipe.ingredientIds.map((id,index)=><div className={`ticket-line ${requiredCounts[index]>=3?"done":""}`} key={id}><Food id={id}/><span>{ingredientById.get(id)!.name}</span><b>{requiredCounts[index]}/3</b></div>)}<div className="ticket-base"><span>{copy.sauce}<b>{state.sauce}%</b></span><span>{copy.cheese}<b>{state.cheese}%</b></span></div></aside>

      <section className={`classic-work classic-${state.station}`}>
        {state.station==="reception"&&<div className="counter-scene"><div className="counter-sign"><span>{copy.orders}</span><b>{state.openOrders.length}</b><small>{copy.arriving} · {nextArrival}s</small></div><div className="counter-customer" style={avatarStyle(recipe.customer.avatar)}/><article className="customer-order"><span>{recipe.customer.role}</span><h2>{recipe.customer.name}</h2><blockquote>“{es?recipe.customer.quote:recipe.customer.quoteEn}”</blockquote><div><small>{copy.requested}</small><b>{recipe.project}</b><div className="mini-recipe">{recipe.ingredientIds.map(id=><span key={id}><Food id={id}/>{ingredientById.get(id)!.name}</span>)}</div></div><button onClick={()=>dispatch({type:"ACCEPT"})}>{copy.take}<ArrowRight/></button></article></div>}

        {state.station==="prep"&&<div className="v2-prep"><div className="work-banner"><span><ChefHat/>{copy.prep}</span><b className={ready?"good":"warn"}>{ready?copy.complete:copy.incomplete}</b></div><div className="recipe-ribbon"><span>{copy.recipe}</span><b>{copy.sauce} {state.sauce}%</b><b>{copy.cheese} {state.cheese}%</b>{recipe.ingredientIds.map((id,index)=><b className={requiredCounts[index]>=3?"done":""} key={id}><Food id={id}/>{ingredientById.get(id)!.name} {requiredCounts[index]}/3</b>)}</div><p className="work-help">{copy.prepHelp}</p><div className="v2-prep-grid"><div className="pizza-bench"><Pizza state={state} mode="prep" onPlace={place}/><div className="base-controls"><button onClick={()=>dispatch({type:"ADD_SAUCE"})}><span style={{width:`${state.sauce}%`}}/><b>{copy.sauce}</b><em>{state.sauce}%</em></button><button onClick={()=>dispatch({type:"ADD_CHEESE"})}><span style={{width:`${state.cheese}%`}}/><b>{copy.cheese}</b><em>{state.cheese}%</em></button></div></div><div className="v2-pantry"><div className="pantry-title"><b>{copy.pantry}</b><span>{state.selected?ingredientById.get(state.selected)!.name:"—"}</span></div><div>{pantry.map(item=><button draggable key={item.id} className={`${state.selected===item.id?"active":""} ${recipe.ingredientIds.includes(item.id)?"required":"extra"}`} onDragStart={event=>{event.dataTransfer.setData("text/topping",item.id);dispatch({type:"SELECT_TOPPING",id:item.id})}} onClick={()=>dispatch({type:"SELECT_TOPPING",id:item.id})}><Food id={item.id}/><span>{item.name}<small>{recipe.ingredientIds.includes(item.id)?copy.recipe:copy.extra}</small></span><b>{state.placements.filter(point=>point.id===item.id).length}</b></button>)}</div><button className="pantry-undo" disabled={!state.placements.length} onClick={()=>dispatch({type:"UNDO"})}><RotateCcw/>{copy.undo}</button></div></div><button className={`work-action ${!ready?"risky":""}`} disabled={!freeOven} onClick={()=>dispatch({type:"BAKE"})}><Flame/>{freeOven?copy.send:copy.full}<ArrowRight/></button></div>}

        {state.station==="oven"&&<div className="v2-ovens"><div className="work-banner"><span><Flame/>{copy.oven}</span><b className={state.cook>103?"danger":""}>{bakeState}</b></div><p className="work-help">{copy.ovenHelp}</p><div className="oven-deck">{state.ovenSlots.map(slot=>{const item=slot.recipeIndex===null?null:RECIPES[slot.recipeIndex];const selected=slot.recipeIndex===state.recipeIndex;return <button className={`${slot.recipeIndex===null?"empty":"loaded"} ${selected?"selected":""} ${slot.cook>103?"burning":""}`} key={slot.slot} disabled={!item} onClick={()=>item&&dispatch({type:"SWITCH_ORDER",index:slot.recipeIndex!})}><div className="oven-plate"><span>DECK 0{slot.slot+1}</span><b>{slot.temperature}°C</b><i>{!item?copy.empty:slot.active?copy.heating:copy.paused}</i></div><div className="oven-mouth">{item?<><div className="oven-mini-pizza" style={{"--cook":Math.min(1,slot.cook/110)} as CSSProperties}/><em>{Math.round(slot.cook)}%</em></>:<Plus/>}</div><strong>{item?.project??copy.open}</strong></button>})}</div>{ovenForCurrent&&<div className="oven-control"><div><Thermometer/><span>{recipe.project}<small>{bakeState} · {Math.round(state.cook)}%</small></span></div><div className="oven-temp"><button onClick={()=>dispatch({type:"TEMP",amount:-15})}><Minus/></button><b>{state.temperature}°</b><button onClick={()=>dispatch({type:"TEMP",amount:15})}><Plus/></button></div><button onClick={()=>dispatch({type:"TOGGLE_OVEN"})}>{state.ovenActive?<><Pause/>{copy.paused}</>:<><Play/>{copy.heating}</>}</button><button className="pull-pizza" onClick={()=>dispatch({type:"TAKE_OUT"})}><Scissors/>{copy.remove}<ArrowRight/></button></div>}</div>}

        {state.station==="cut"&&<div className="v2-cut-scene"><div className="work-banner"><span><Scissors/>{copy.cut}</span><b>{state.cuts.length}/{recipe.targetCuts/2}</b></div><p className="work-help">{copy.cutHelp}</p><div className="cutting-table"><Pizza state={state} mode="cut" onCut={(x1,y1,x2,y2)=>dispatch({type:"ADD_CUT",cut:{x1,y1,x2,y2}})}/><aside><small>{copy.requested}</small><b>{recipe.targetCuts}</b><span>{es?"porciones":"slices"}</span><button onClick={()=>dispatch({type:"AUTO_CUT"})}><Check/>{copy.precision}</button><button onClick={()=>dispatch({type:"RESTART_ORDER"})}><RotateCcw/>{copy.redo}</button></aside></div><button className="work-action risky" onClick={()=>dispatch({type:"FINISH"})}><Check/>{copy.deliver}<ArrowRight/></button></div>}

        {state.station==="result"&&state.result&&<div className="v2-result"><span>{copy.result}</span><div className="result-avatar" style={avatarStyle(recipe.customer.avatar)}/><h2>{recipe.project}</h2><div className="v2-stars">{Array.from({length:5},(_,index)=><i className={index<state.result!.stars?"on":""} key={index}>★</i>)}</div><div className="v2-score-grid">{[[es?"Pedido":"Order",state.result.order],[es?"Distribución":"Distribution",state.result.distribution],[es?"Cocción":"Bake",state.result.bake],[es?"Corte":"Cut",state.result.cut],[es?"Servicio":"Service",state.result.service]].map(([label,value])=><div key={String(label)}><span>{label}</span><b>{value}</b><i><em style={{width:`${value}%`}}/></i></div>)}</div><strong>{state.result.total.toString().padStart(4,"0")}</strong><div className="v2-result-actions"><button onClick={()=>dispatch({type:"NEXT"})}>{copy.nextOrder}<ArrowRight/></button><a href={recipe.repo} target="_blank" rel="noreferrer"><GitBranch/>{copy.repo}</a></div></div>}
      </section>
    </div>
    <footer className="classic-footer"><span>{DIFFICULTIES[state.difficulty].name} · {state.openOrders.length} {copy.orders.toLowerCase()}</span><a href="mailto:ignacio.schwindt.dev@gmail.com"><Contact/>ignacio.schwindt.dev@gmail.com</a></footer>
  </main>;
}
