export const copy = {
  es: {
    play: "Jugar turno",
    portfolio: "Portfolio",
    portfolioQuick: "Portfolio rápido",
    resume: "Continuar partida",
    settings: "Ajustes",
    credits: "Créditos",
    selectLevel: "Elegí una receta inicial",
    selectPace: "Ritmo de servicio",
    premise: "Construyo el puente entre la lógica de alto nivel y las señales de bajo nivel.",
    homeNote: "Un portfolio que se entiende jugando.",
    reception: "Recepción",
    prep: "Preparación",
    oven: "Horno",
    cut: "Corte",
    order: "Comanda",
    queue: "en espera",
    patience: "Paciencia",
    accept: "Tomar pedido",
    requested: "El cliente pidió",
    sauce: "Salsa",
    cheese: "Queso",
    toppings: "Componentes / toppings",
    prepHelp: "Aplicá salsa y queso. Después elegí cada componente y colocá al menos 3 piezas bien distribuidas.",
    selected: "Topping seleccionado",
    undo: "Deshacer último",
    bake: "Enviar al horno",
    missing: "Completá cobertura y componentes",
    heat: "Temperatura",
    ovenHelp: "Controlá la temperatura y retirala cuando la cocción esté en la zona perfecta. Si te distraés, se quema.",
    pause: "Pausar horno",
    resumeOven: "Encender horno",
    remove: "Retirar pizza",
    raw: "Cruda",
    cooking: "Cocinando",
    perfect: "En su punto",
    burning: "¡Se quema!",
    burnt: "Quemada",
    cutHelp: "Arrastrá el cortador cruzando el centro. Hacé cortes parejos para obtener las porciones pedidas.",
    precise: "Corte accesible preciso",
    deliver: "Entregar proyecto",
    slices: "porciones",
    result: "Servicio completado",
    orderScore: "Pedido",
    distribution: "Distribución",
    bakeScore: "Cocción",
    cutScore: "Corte",
    service: "Servicio",
    next: "Siguiente cliente",
    openRepo: "Abrir proyecto real",
    restart: "Rehacer pedido",
    total: "Puntaje total",
    projects: "Proyectos seleccionados",
    stack: "Stack completo",
    back: "Volver al juego",
    backHome: "Volver al portfolio",
    viewCode: "Ver código",
    language: "Idioma",
    sound: "Sonido",
    made: "Diseño, arte y código originales",
    level: "Nivel",
  },
  en: {
    play: "Start shift",
    portfolio: "Portfolio",
    portfolioQuick: "Quick portfolio",
    resume: "Continue game",
    settings: "Settings",
    credits: "Credits",
    selectLevel: "Choose a starting recipe",
    selectPace: "Service pace",
    premise: "I bridge the gap between high-level logic and low-level signals.",
    homeNote: "A portfolio you understand by playing.",
    reception: "Front counter",
    prep: "Preparation",
    oven: "Oven",
    cut: "Cut",
    order: "Order ticket",
    queue: "waiting",
    patience: "Patience",
    accept: "Take order",
    requested: "The customer ordered",
    sauce: "Sauce",
    cheese: "Cheese",
    toppings: "Components / toppings",
    prepHelp: "Apply sauce and cheese. Then choose every component and place at least 3 pieces with good distribution.",
    selected: "Selected topping",
    undo: "Undo last",
    bake: "Send to oven",
    missing: "Complete coverage and components",
    heat: "Temperature",
    ovenHelp: "Control the heat and pull the pizza in the perfect zone. Leave it too long and it will burn.",
    pause: "Pause oven",
    resumeOven: "Start oven",
    remove: "Pull pizza",
    raw: "Raw",
    cooking: "Cooking",
    perfect: "Perfect",
    burning: "Burning!",
    burnt: "Burnt",
    cutHelp: "Drag the cutter across the center. Make even cuts for the requested number of slices.",
    precise: "Accessible precision cut",
    deliver: "Deliver project",
    slices: "slices",
    result: "Service complete",
    orderScore: "Order",
    distribution: "Distribution",
    bakeScore: "Bake",
    cutScore: "Cut",
    service: "Service",
    next: "Next customer",
    openRepo: "Open real project",
    restart: "Redo order",
    total: "Total score",
    projects: "Selected projects",
    stack: "Full stack",
    back: "Back to game",
    backHome: "Back to portfolio",
    viewCode: "View code",
    language: "Language",
    sound: "Sound",
    made: "Original design, art and code",
    level: "Level",
  },
} as const;
